name: shoko_anime_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  shared_preferences_android: ^2.2.0
  shared_preferences_foundation: ^2.3.0
  shared_preferences_windows: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.2.3
  icons_plus: ^4.0.0
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/login_bg_desktop.png
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
  macos:
    generate: true
    image_path: "assets/logo.png"
